apiVersion: v1
kind: Service
metadata:
  name: postgres-default
  labels:
    tier: database
spec:
  ports:
  - name: postgresql
    nodePort: 0
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    name: postgres-default
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
